#### WEB SCRAPING – ASSIGNMENT 4

#### Intern Name: Lakshminarayanareddy Marapareddygarihanumanthu
#### Internship Number: DS2405

In [1]:
# Install and import required modules 
!pip install selenium

import selenium
import pandas as pd   # To create a data frame using scraped data
from selenium import webdriver  # Allows you to launch/initialise a browser
import time   # Allows to pause the webdriver for user specified time
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By   # Allows you to search for things using specific parameters like ID, Class name,...

# Importing exception handling 
from selenium.common.exceptions import NoSuchElementException  
from selenium.common.exceptions import StaleElementReferenceException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

Requirement already satisfied: selenium in /home/lreddy/anaconda3/lib/python3.9/site-packages (4.22.0)
Requirement already satisfied: websocket-client>=1.8.0 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from selenium) (1.8.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from selenium) (1.26.11)
Requirement already satisfied: typing_extensions>=4.9.0 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from selenium) (4.9.0)
Requirement already satisfied: trio-websocket~=0.9 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from selenium) (2024.7.4)
Requirement already satisfied: trio~=0.17 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from selenium) (0.25.1)
Requirement already satisfied: sortedcontainers in /home/lreddy/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=23.2.0 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: exceptiongroup in /home/lreddy/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.2.1)
Requirement already satisfied: idna in /home/lreddy/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sniffio>=1.3.0 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: outcome in /home/lreddy/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: wsproto>=0.14 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /home/lreddy/anaconda3/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

1. Scrape the details of most viewed videos on YouTube from Wikipedia.Url 
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: 
A)Rank
B) Name
C) Artist
D) Upload date
E) Views

In [2]:
# Initialize the Chrome driver
driver1 = webdriver.Chrome()
# Opening web page on automated Chrome browser
driver1.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')  
# Pausing the webdriver for 4 seconds
time.sleep(4)

In [3]:
# Empty list to strore scraped rank data
rank = []

# Locating rank
rank_list = driver1.find_elements(By.XPATH,"//div[@id='mw-content-text']/div[1]/table[1]/tbody/tr") 
# Scraping the rank of most viewedYouTube video
for i in rank_list:
    try:
        if i.text is None:
            rank.append("--")
        else:
            rank.append(rank_list.index(i)+1)
    except NoSuchElementException as e:
        rank.append("--")
        
print(len(rank))
print(rank)

30
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [12]:
# Empty list to store name of the video
video_name = []

# scraping most viewed video Name and appending list 
vn = driver1.find_elements(By.XPATH,"//div[@id='mw-content-text']/div[1]/table[1]/tbody/tr/td[1]")
for i in vn:
    if i.text is None :
        video_name.append("--") 
    else:
        video_name.append(i.text)
        
print(len(video_name))
print(video_name)

30
['"Baby Shark Dance"[7]', '"Despacito"[10]', '"Johny Johny Yes Papa"[18]', '"Bath Song"[19]', '"Wheels on the Bus"[20]', '"See You Again"[21]', '"Shape of You"[26]', '"Phonics Song with Two Words"[29]', '"Uptown Funk"[30]', '"Gangnam Style"[31]', '"Learning Colors – Colorful Eggs on a Farm"[36]', '"Dame Tu Cosita"[37]', '"Axel F"[38]', '"Masha and the Bear – Recipe for Disaster"[39]', '"Baa Baa Black Sheep"[40]', '"Lakdi Ki Kathi"[41]', '"Sugar"[42]', '"Counting Stars"[43]', '"Roar"[44]', '"Waka Waka (This Time for Africa)"[45]', '"Shree Hanuman Chalisa"[46]', '"Humpty the train on a fruits ride"[47]', '"Sorry"[48]', '"Thinking Out Loud"[49]', '"Perfect"[50]', '"Dark Horse"[51]', '"Let Her Go"[52]', '"Faded"[53]', '"Girls Like You"[54]', '"Lean On"[55]']

In [15]:
# Empty list to store artist of the video
artist_name = []

# Scraping the artist name
artist = driver1.find_elements(By.XPATH,"//div[@id='mw-content-text']/div[1]/table[1]/tbody/tr/td[2]")
for i in artist:
    if i.text is None :
        artist_name.append("--") 
    else:
        artist_name.append(i.text)
        
print(len(artist_name),artist_name)

30 ["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', "LooLoo Kids - Nursery Rhymes and Children's Songs", 'Cocomelon - Nursery Rhymes', 'Cocomelon - Nursery Rhymes', 'Wiz Khalifa', 'Ed Sheeran', 'ChuChu TV Nursery Rhymes & Kids Songs', 'Mark Ronson', 'Psy', 'Miroshka TV', 'Ultra Records', 'Crazy Frog', 'Get Movies', 'Cocomelon - Nursery Rhymes', 'Jingle Toons', 'Maroon 5', 'OneRepublic', 'Katy Perry', 'Shakira', 'T-Series Bhakti Sagar', 'Kiddiestv Hindi - Nursery Rhymes & Kids Songs', 'Justin Bieber', 'Ed Sheeran', 'Ed Sheeran', 'Katy Perry', 'Passenger', 'Alan Walker', 'Maroon 5', 'Major Lazer Official']

In [16]:
# Empty list to store uploaded date of the video
upload_date = []

#scraping the upload_date 
date = driver1.find_elements(By.XPATH,"//div[@id='mw-content-text']/div[1]/table[1]/tbody/tr/td[4]")
for i in date:
    if i.text is None :
        upload_date.append("--") 
    else:
        upload_date.append(i.text)
        
print(len(upload_date),upload_date)

30 ['June 17, 2016', 'January 12, 2017', 'October 8, 2016', 'May 2, 2018', 'May 24, 2018', 'April 6, 2015', 'January 30, 2017', 'March 6, 2014', 'November 19, 2014', 'July 15, 2012', 'February 27, 2018', 'April 5, 2018', 'June 16, 2009', 'January 31, 2012', 'June 25, 2018', 'June 14, 2018', 'January 14, 2015', 'May 31, 2013', 'September 5, 2013', 'June 4, 2010', 'May 10, 2011', 'January 26, 2018', 'October 22, 2015', 'October 7, 2014', 'November 9, 2017', 'February 20, 2014', 'July 25, 2012', 'December 3, 2015', 'May 31, 2018', 'March 22, 2015']

In [17]:
# Empty list to store no. of views of the video
views = []

#scraping views
vs = driver1.find_elements(By.XPATH,"//div[@id='mw-content-text']/div[1]/table[1]/tbody/tr/td[3]")
for i in vs:
    if i.text is None :
        views.append("--") 
    else:
        views.append(i.text)
        
print(len(views),views)

30 ['14.82', '8.49', '6.94', '6.79', '6.34', '6.33', '6.30', '5.90', '5.28', '5.22', '5.15', '4.72', '4.66', '4.59', '4.14', '4.11', '4.08', '4.05', '4.03', '3.99', '3.94', '3.87', '3.83', '3.79', '3.77', '3.76', '3.69', '3.66', '3.64', '3.64']

In [18]:
# Creating adata frame
mvv_df = pd.DataFrame({'Rank': rank, 'Video title': video_name, 'Artist name': artist_name, 'Uplod date': upload_date, 'Views in billion': views})
mvv_df

,Rank,Video title,Artist name,Uplod date,Views in billion
0,1,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.82
1,2,"""Despacito""[10]",Luis Fonsi,"January 12, 2017",8.49
2,3,"""Johny Johny Yes Papa""[18]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.94
3,4,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.79
4,5,"""Wheels on the Bus""[20]",Cocomelon - Nursery Rhymes,"May 24, 2018",6.34
5,6,"""See You Again""[21]",Wiz Khalifa,"April 6, 2015",6.33
6,7,"""Shape of You""[26]",Ed Sheeran,"January 30, 2017",6.30
7,8,"""Phonics Song with Two Words""[29]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.90
8,9,"""Uptown Funk""[30]",Mark Ronson,"November 19, 2014",5.28
9,10,"""Gangnam Style""[31]",Psy,"July 15, 2012",5.22
10,11,"""Learning Colors – Colorful Eggs on a Farm""[36]",Miroshka TV,"February 27, 2018",5.15
11,12,"""Dame Tu Cosita""[37]",Ultra Records,"April 5, 2018",4.72
12,13,"""Axel F""[38]",Crazy Frog,"June 16, 2009",4.66
13,14,"""Masha and the Bear – Recipe for Disaster""[39]",Get Movies,"January 31, 2012",4.59
14,15,"""Baa Baa Black Sheep""[40]",Cocomelon - Nursery Rhymes,"June 25, 2018",4.14
15,16,"""Lakdi Ki Kathi""[41]",Jingle Toons,"June 14, 2018",4.11
16,17,"""Sugar""[42]",Maroon 5,"January 14, 2015",4.08
17,18,"""Counting Stars""[43]",OneRepublic,"May 31, 2013",4.05
18,19,"""Roar""[44]",Katy Perry,"September 5, 2013",4.03
19,20,"""Waka Waka (This Time for Africa)""[45]",Shakira,"June 4, 2010",3.99
20,21,"""Shree Hanuman Chalisa""[46]",T-Series Bhakti Sagar,"May 10, 2011",3.94
21,22,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.87
22,23,"""Sorry""[48]",Justin Bieber,"October 22, 2015",3.83
23,24,"""Thinking Out Loud""[49]",Ed Sheeran,"October 7, 2014",3.79
24,25,"""Perfect""[50]",Ed Sheeran,"November 9, 2017",3.77
25,26,"""Dark Horse""[51]",Katy Perry,"February 20, 2014",3.76
26,27,"""Let Her Go""[52]",Passenger,"July 25, 2012",3.69
27,28,"""Faded""[53]",Alan Walker,"December 3, 2015",3.66
28,29,"""Girls Like You""[54]",Maroon 5,"May 31, 2018",3.64
29,30,"""Lean On""[55]",Major Lazer Official,"March 22, 2015",3.64

In [19]:
#Close the browser session 
driver1.close()

2. Scrape the details team India’s international fixtures from bcci.tv. 
Url = https://www.bcci.tv/.
You need to find following details:
A) Series
B) Place
C) Date
D) Time
Note:- From bcci.tv home page you have reach to the international fixture page through code.

In [2]:
# Initialize the Chrome driver
driver2 = webdriver.Chrome()
# Opening web page on automated Chrome browser
driver2.get('https://www.bcci.tv/')  
# Pausing the webdriver for 4 seconds
time.sleep(4)

In [3]:
# Click the international tab
international = driver2.find_element(By.XPATH,"//*[@id='pills-international-tab']")
international.click()
# Pausing the webdriver for 4 seconds
time.sleep(4)

In [4]:
# Click the Fixtures tab
fixtures = driver2.find_element(By.XPATH,"/html/body/header/div[3]/div[2]/ul/div[1]/a[2]")
fixtures.click()
# Pausing the webdriver for 4 seconds
time.sleep(4)

In [5]:
# Click more matches tab
more_matches = driver2.find_element(By.XPATH,"//div[@class='col-lg-12 col-md-12 col-sm-12']")
more_matches.click()
# Pausing the webdriver for 4 seconds
time.sleep(4)

In [6]:
# Empty lists to store scraped data
series = []
place = []
date = []
time = []

In [8]:
#scraping the series name 
sn = driver2.find_elements(By.XPATH,"//div[@class='match-info']/h5")
for i in sn:
    if i.text is None :
        series.append("--") 
    else:
        series.append(i.text)
        
print(len(series),series)

15 ['India Tour Of Sri Lanka T20 Series 2024', 'India Tour Of Sri Lanka ODI Series 2024', 'India Tour Of Sri Lanka ODI Series 2024', 'India Tour Of Sri Lanka ODI Series 2024', 'Bangladesh Tour Of India Test Series 2024', 'Bangladesh Tour Of India Test Series 2024', 'ICC Womens T20 World Cup 2024', 'ICC Womens T20 World Cup 2024', 'Bangladesh Tour Of India T20 Series 2024', 'ICC Womens T20 World Cup 2024', 'Bangladesh Tour Of India T20 Series 2024', 'Bangladesh Tour Of India T20 Series 2024', 'ICC Womens T20 World Cup 2024', 'New Zealand Tour Of India Test Series 2024', 'New Zealand Tour Of India Test Series 2024']

In [9]:
#scraping the place name 
gp = driver2.find_elements(By.XPATH,"//div[@class='match-venue ng-scope']")
for i in gp:
    if i.text is None :
        place.append("--") 
    else:
        place.append(i.text)
        
print(len(place),place)

15 ['Pallekele International Cricket Stadium, Pallekele', 'R Premadasa International Stadium, Colombo', 'R Premadasa International Stadium, Colombo', 'R Premadasa International Stadium, Colombo', 'MA Chidambaram Stadium, Chennai', 'Green Park, Kanpur', 'Sylhet International Cricket Stadium, Sylhet', 'Sylhet International Cricket Stadium, Sylhet', 'Himachal Pradesh Cricket Association Stadium, Dharamsala', 'Sylhet International Cricket Stadium, Sylhet', 'Arun Jaitley Stadium, Delhi', 'Rajiv Gandhi International Stadium, Hyderabad', 'Sylhet International Cricket Stadium, Sylhet', 'M Chinnaswamy Stadium, Bengaluru', 'Maharashtra Cricket Association Stadium, Pune']

In [10]:
#scraping date  
day = driver2.find_elements(By.XPATH,"//div[@class='match-date-info']/div[1]")
for i in day:
    if i.text is None :
        date.append("--") 
    else:
        date.append(i.text)
        
print(len(date),date)

15 ['30 Jul', '2 Aug', '4 Aug', '7 Aug', '19 Sep', '27 Sep', '4 Oct', '6 Oct', '6 Oct', '9 Oct', '9 Oct', '12 Oct', '13 Oct', '16 Oct', '24 Oct']

In [11]:
#scraping time
tim = driver2.find_elements(By.XPATH,"//div[@class='match-date-info']/div[2]")
for i in tim:
    if i.text is None :
        time.append("--") 
    else:
        time.append(i.text)
        
print(len(time),time)

15 ['14:30 BST', '10:00 BST', '10:00 BST', '10:00 BST', '5:00 BST', '5:00 BST', '14:00', '14:00', '14:30 BST', '14:00', '14:30 BST', '14:30 BST', '14:00', '5:00 BST', '5:00 BST']

In [12]:
# Creating adata frame
indiafixtures_df = pd.DataFrame({'Series': series, 'Ground': place, 'Date (2024)': date, 'Time': time})

indiafixtures_df

,Series,Ground,Date (2024),Time
0,India Tour Of Sri Lanka T20 Series 2024,"Pallekele International Cricket Stadium, Palle...",30 Jul,14:30 BST
1,India Tour Of Sri Lanka ODI Series 2024,"R Premadasa International Stadium, Colombo",2 Aug,10:00 BST
2,India Tour Of Sri Lanka ODI Series 2024,"R Premadasa International Stadium, Colombo",4 Aug,10:00 BST
3,India Tour Of Sri Lanka ODI Series 2024,"R Premadasa International Stadium, Colombo",7 Aug,10:00 BST
4,Bangladesh Tour Of India Test Series 2024,"MA Chidambaram Stadium, Chennai",19 Sep,5:00 BST
5,Bangladesh Tour Of India Test Series 2024,"Green Park, Kanpur",27 Sep,5:00 BST
6,ICC Womens T20 World Cup 2024,"Sylhet International Cricket Stadium, Sylhet",4 Oct,14:00
7,ICC Womens T20 World Cup 2024,"Sylhet International Cricket Stadium, Sylhet",6 Oct,14:00
8,Bangladesh Tour Of India T20 Series 2024,"Himachal Pradesh Cricket Association Stadium, ...",6 Oct,14:30 BST
9,ICC Womens T20 World Cup 2024,"Sylhet International Cricket Stadium, Sylhet",9 Oct,14:00
10,Bangladesh Tour Of India T20 Series 2024,"Arun Jaitley Stadium, Delhi",9 Oct,14:30 BST
11,Bangladesh Tour Of India T20 Series 2024,"Rajiv Gandhi International Stadium, Hyderabad",12 Oct,14:30 BST
12,ICC Womens T20 World Cup 2024,"Sylhet International Cricket Stadium, Sylhet",13 Oct,14:00
13,New Zealand Tour Of India Test Series 2024,"M Chinnaswamy Stadium, Bengaluru",16 Oct,5:00 BST
14,New Zealand Tour Of India Test Series 2024,"Maharashtra Cricket Association Stadium, Pune",24 Oct,5:00 BST

In [13]:
#Close the browser session 
driver2.close()

3. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details: A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note:- From statisticstimes home page you have to reach to economy page through code.

In [2]:
# Initialize the Chrome driver
driver3 = webdriver.Chrome()
# Opening web page on automated Chrome browser
driver3.get('http://statisticstimes.com/')

In [3]:
# Click the Economy tab
economy_page = driver3.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/button")
economy_page.click()
# select India tab
ind_page = driver3.find_element(By.XPATH,"//div[@class='navbar']/div[2]/div/a[3]")
ind_page.click()

In [15]:
rank = []
#scraping the Rank 
state_rank = driver3.find_elements(By.XPATH, "//td[@class='data1']")
for i in state_rank:
    if i.text is None :
        rank.append("--") 
        
    else:
        rank.append(i.text)
        
for elt in rank:
    if elt == ',' or elt == '':
        rank.remove(elt)
        
print(len(rank),rank)

66 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33']

In [17]:
state_name = []

#scraping the State names 
states = driver3.find_elements(By.XPATH, "//td[@class='name']")
for i in states:
    if i.text is None :
        state_name.append("--") 
    else:
        state_name.append(i.text)
        
for elt in state_name:
    if elt == 'India':
        state_name.remove(elt)
        
print(len(state_name),state_name)

66 ['Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Odisha', 'Bihar', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Odisha', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Manipur', 'Sikkim', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands']

In [9]:
GSDP_2223 = []
#scraping the GSDP of 2022 -23 
gsdp2223 = driver3.find_elements(By.XPATH, "//table[@class='display dataTable']/tbody/tr/td[4]")
for i in gsdp2223:
    if i.text is None :
        GSDP_2223.append("-") 
    else:
        GSDP_2223.append(i.text)
        
print(len(GSDP_2223),GSDP_2223)

66 ['-', '2,364,514', '2,269,995', '2,258,040', '2,230,609', '1,531,758', '1,365,849', '1,303,524', '1,308,034', '1,246,471', '1,046,188', '1,014,688', '984,055', '753,177', '751,396', '676,164', '493,167', '464,399', '393,722', '303,781', '224,226', '191,728', '93,672', '72,636', '54,285', '49,643', '42,697', '42,756', '-', '39,630', '35,643', '-', '-', '-', '2,115,510', '2,055,658', '1,962,865', '1,946,334', '1,378,859', '1,222,507', '1,167,107', '1,184,237', '1,137,254', '933,564', '911,639', '885,029', '681,761', '670,196', '588,712', '428,072', '412,494', '360,689', '267,653', '181,383', '163,062', '83,711', '65,808', '48,261', '44,809', '37,925', '-', '35,670', '35,555', '30,957', '-', '-']

In [10]:
GSDP_2122 = []
#scraping the GSDP of 2021 -22 
gsdp2122 = driver3.find_elements(By.XPATH, "//table[@class='display dataTable']/tbody/tr/td[5]")
for i in gsdp2122:
    if i.text is None :
        GSDP_2122.append("-") 
    else:
        GSDP_2122.append(i.text)
        
print(len(GSDP_2122),GSDP_2122)

66 ['3,108,022', '2,071,286', '1,978,094', '1,975,595', '1,928,683', '1,329,238', '1,193,489', '1,148,471', '1,124,204', '1,092,964', '934,542', '881,336', '868,905', '662,886', '650,302', '617,192', '411,454', '410,525', '358,863', '267,143', '193,352', '172,162', '84,266', '62,550', '46,096', '43,810', '38,785', '37,557', '36,594', '34,775', '31,038', '27,824', '10,371', '2,690,525', '1,854,109', '1,790,456', '1,715,328', '1,700,504', '1,199,587', '1,068,864', '1,030,465', '1,017,859', '993,235', '825,010', '782,570', '778,885', '589,712', '579,905', '540,097', '366,359', '365,028', '325,830', '235,376', '156,907', '145,182', '74,305', '56,226', '41,011', '39,787', '34,441', '32,874', '31,519', '31,420', '26,924', '24,293', '9,209']

In [11]:
share_2122 = []
#scraping share in 2021 -22 
share = driver3.find_elements(By.XPATH, "//table[@class='display dataTable']/tbody/tr/td[6]")
for i in share:
    if i.text is None :
        share_2122.append("-") 
    else:
        share_2122.append(i.text)
        
print(len(share_2122),share_2122)

66 ['13.17%', '8.78%', '8.38%', '8.37%', '8.17%', '5.63%', '5.06%', '4.87%', '4.76%', '4.63%', '3.96%', '3.73%', '3.68%', '2.81%', '2.76%', '2.62%', '1.74%', '1.74%', '1.52%', '1.13%', '0.82%', '0.73%', '0.36%', '0.27%', '0.20%', '0.19%', '0.16%', '0.16%', '0.16%', '0.15%', '0.13%', '0.12%', '0.04%', '13.03%', '8.98%', '8.67%', '8.31%', '8.23%', '5.81%', '5.18%', '4.99%', '4.93%', '4.81%', '3.99%', '3.79%', '3.77%', '2.86%', '2.81%', '2.62%', '1.77%', '1.77%', '1.58%', '1.14%', '0.76%', '0.70%', '0.36%', '0.27%', '0.20%', '0.19%', '0.17%', '0.16%', '0.15%', '0.15%', '0.13%', '0.12%', '0.04%']

In [12]:
GDP_2021 = []
#scraping the GDP of 2021 -22 
gdp = driver3.find_elements(By.XPATH, "//table[@class='display dataTable']/tbody/tr/td[7]")
for i in gdp:
    if i.text is None :
        GDP_2021.append("-") 
    else:
        GDP_2021.append(i.text)
        
print(len(GDP_2021),GDP_2021)

66 ['414.928', '276.522', '264.080', '263.747', '257.484', '177.456', '159.334', '153.324', '150.084', '145.913', '124.764', '117.660', '116.001', '88.497', '86.817', '82.397', '54.930', '54.806', '47.909', '35.664', '25.813', '22.984', '11.250', '8.351', '6.154', '5.849', '5.178', '5.014', '4.885', '4.643', '4.144', '3.715', '1.385', '-', '1,384,921', '1,263,925', '1,206,156', '-', '791,144', '737,042', '723,343', '679,552', '579,234', '-', '590,836', '561,368', '-', '443,233', '424,857', '288,842', '279,803', '-', '186,484', '108,830', '120,733', '-', '-', '-', '-', '23,063', '-', '-', '-', '-', '-', '-']

In [18]:
# Creating adata frame
states_df = pd.DataFrame({'Rank': rank, 'State': state_name, 'GSDP (2022-23)': GSDP_2223, 'GSDP (2021-22)': GSDP_2122, 'Share in GDP (2021-22)': share_2122, 'GDP ($ billion)': GDP_2021})

states_df

,Rank,State,GSDP (2022-23),GSDP (2021-22),Share in GDP (2021-22),GDP ($ billion)
0,1,Maharashtra,-,"3,108,022",13.17%,414.928
1,2,Tamil Nadu,"2,364,514","2,071,286",8.78%,276.522
2,3,Karnataka,"2,269,995","1,978,094",8.38%,264.080
3,4,Uttar Pradesh,"2,258,040","1,975,595",8.37%,263.747
4,5,Gujarat,"2,230,609","1,928,683",8.17%,257.484
...,...,...,...,...,...,...
61,29,Sikkim,"35,670","31,519",0.15%,-
62,30,Arunachal Pradesh,"35,555","31,420",0.15%,-
63,31,Nagaland,"30,957","26,924",0.13%,-
64,32,Mizoram,-,"24,293",0.12%,-
65,33,Andaman & Nicobar Islands,-,"9,209",0.04%,-

In [19]:
#Close the browser session 
driver3.close()

4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note:- From the home page you have to click on the trending option from Explore menu through code.

In [21]:
# Initialize the Chrome driver
driver4 = webdriver.Chrome()
# Opening web page on automated Chrome browser
driver4.get('https://github.com/')

5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the
following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note:- From the home page you have to click on the charts option then hot 100-page link through code.

6. Scrape the details of Highest selling novels.
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre
Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

7. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/ You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

8. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/ You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute G) Year

Note:- from the home page you have to go to the Show All Dataset page through code.